---
- name: Create pods using deployment 
  hosts: manager
  user: root
 
  tasks: 
  - name: create a deployment
    command: kubectl apply -f /opt/kuber/kube-deploy.yml

  - name: update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment.apps/test-deployment 
